# Generated by Django 4.0.5 on 2022-06-22 13:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='end_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 9, 20, 22, 6, 37, 105496)),
        ),
        migrations.AlterField(
            model_name='article',
            name='start_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 6, 22, 22, 6, 37, 105496)),
        ),
    ]
