# Generated by Django 4.0.5 on 2022-06-20 11:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_article_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='end_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 9, 18, 20, 1, 10, 210880)),
        ),
    ]
