# Generated by Django 4.0.5 on 2022-06-20 13:13

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0003_alter_article_end_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='desc',
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ManyToManyField(related_name='cateogry', to='blog.category'),
        ),
        migrations.AlterField(
            model_name='article',
            name='end_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 9, 18, 22, 13, 37, 622722)),
        ),
        migrations.AlterField(
            model_name='article',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
