# Generated by Django 4.0.5 on 2022-06-22 13:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_article_end_time_alter_article_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='end_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 9, 20, 22, 19, 34, 718895)),
        ),
        migrations.AlterField(
            model_name='article',
            name='start_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 6, 22, 22, 19, 34, 718895)),
        ),
    ]
