# Generated by Django 4.0.5 on 2022-06-21 11:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_article_category_alter_article_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='end_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 9, 19, 20, 25, 56, 599633)),
        ),
        migrations.AlterField(
            model_name='article',
            name='start_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 6, 21, 20, 25, 56, 599633)),
        ),
    ]
