# Generated by Django 4.0.5 on 2022-06-21 11:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_article_end_time_alter_article_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='end_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 9, 19, 20, 29, 30, 97513)),
        ),
        migrations.AlterField(
            model_name='article',
            name='start_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 6, 21, 20, 29, 30, 97513)),
        ),
    ]
